/* temp_model.h
 *
 * This contains the temperature profile / model to be loaded
 * into ROM on bootup for the optimal DC calculation
 *
 * (file auto-generated by python script)
 *
 */

#ifndef _TEMP_MODEL_H
#define _TEMP_MODEL_H

// =============== TEMP MODELS GIVEN AN INDEX (bc,nc,wc) ==============
const int temp_model_num_bins[3] = {10,10,10};
const int temp_model_start_temp[3] = {-3,-30,0};
const int temp_model_leftmost_edge[3] = {-4,-34,-2};
const float temp_model_bin_width[3] = {2.33, 6.96, 5.41};
const char temp_model_hist[3][10] = {
{
0,
8,
50,
102,
122,
100,
74,
37,
11,
1
},

{
0,
10,
31,
53,
80,
78,
89,
103,
54,
7
},

{
1,
23,
63,
80,
76,
69,
77,
67,
45,
6
}
};


// ============== FOR KEEPING TRACK OF WINDOWED HISTOGRAM ==============
unsigned int temp_hist_numpoints = 0;
unsigned int temp_hist_windowed[TEMP_MODEL_NUM_BINS] = {
0,
0,
0,
0,
0,
0,
0,
0,
0,
0
};


#endif /* _TEMP_MODEL_H */
